#!/usr/bin/env zsh

alias containers-fix="sudo restorecon -RFv /var/lib/containers/storage"
alias update-kitty="curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n"

# Completions
autoload -Uz compinit && compinit -u
zstyle ':completion:*' menu select
zstyle ':completion:*' completer _approximate
zstyle ':completion:*' matcher-list '' \
    'm:{[:lower:]}={[:upper:]}' \
    '+r:|[._-]=* r:|=*' \
    '+l:|=*'

# Descriptions for the various types of completions
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*' group-name ''

# Make it clear when potential errors are being corrected
zstyle ':completion:*:*:*:*:corrections' format '%F{yellow}!- %d (errors: %e) -!%f'

# Git stuff
autoload -Uz vcs_info # VCS info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT='${vcs_info_msg_0_}'
zstyle ':vcs_info:git:*' formats '%b' # Display on the left side of the screen

# Home/End/Delete keys
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[[3~"  delete-char

# Different prompt colours for each distro
NAME_COLOUR="magenta"
DIR_COLOUR="blue"
SHOW_FASTFETCH=true
SHOW_SYSEXT=true

if [[ "$(hostname)" == *"debian"* ]]; then
	
	# red
	NAME_COLOUR="#ff6961"
	# orange
	DIR_COLOUR="#ffb347"

	# Don't show in distrobox
	SHOW_SYSEXT=false

elif [[ "$(hostname)" == *"arch"* ]]; then

	# dark blue
	NAME_COLOUR="#779ecb"
	# light blue
	DIR_COLOUR="#aec6cf"

	# Don't show in distrobox
	SHOW_SYSEXT=false

elif [[ "$(hostname)" == *"fedora"* ]]; then
	
	# light blue
	NAME_COLOUR="#aec6cf"
	# red
	DIR_COLOUR="#cfaec6"

	# Don't show in distrobox
	SHOW_SYSEXT=false

elif [[ "$(pwd)" =~ ".local/share/chezmoi" ]]; then

		# pink
		DIR_COLOUR="#ffd1dc"

		# Don't show in chezmoi cd
		SHOW_FASTFETCH=false
		SHOW_SYSEXT=false

		# Show changes not yet staged/committed in git
		git status

		# Show files modified by chezmoi
		chezmoi status

fi

# Include the /usr/games directory where Debian puts games
export PATH=$PATH:/usr/games

# Make sure $SHELL is set to zsh while in the interactive shell
export SHELL=$(which zsh)

# Pick the prompt colour then unset the variable for it
PS1="%B%F{$NAME_COLOUR}%n@%m %F{$DIR_COLOUR}%~%F{$DIR_COLOUR}$ %f%b"
unset NAME_COLOUR
unset DIR_COLOUR

if env | grep -Fq 'DISTROBOX'; then

else
	# Arch distrobox
	alias archbtw="distrobox enter Arch"

	# Auto suggestions
	source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

	# Syntax highlighting
	source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

	# sudo -> run0 alias
	# Put it here so it is *not* active in containers
	alias sudo="run0 --via-shell --background=''"

fi

# Only show if we want them to be shown
if $SHOW_FASTFETCH; then
	fastfetch
fi

if $SHOW_SYSEXT; then
	systemd-sysext status
fi
