### Output configuration
#
# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
# Requires: desktop-backgrounds-compat, swaybg, jxl-pixbuf-loader

# 1440p gaming monitor
output DP-2 {
    pos 0 0 
    res 2560x1440@165.080hz
#    adaptive_sync on 
    allow_tearing true
#    render_bit_depth 10
}

# 1080p secondary monitor
output HDMI-A-1 {
    pos 2560 180
    res 1920x1080
}

output * max_render_time off

workspace 1 output DP-2
workspace 2 output DP-2
workspace 3 output DP-2
workspace 4 output DP-2
workspace 5 output DP-2
workspace 6 output HDMI-A-1
workspace 7 output HDMI-A-1
workspace 8 output HDMI-A-1
workspace 9 output HDMI-A-1
workspace 10 output HDMI-A-1

#
# Example configuration:
#
#   output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# You can get the names of your outputs by running: swaymsg -t get_outputs


# hacky workaround before switching main PC over
exec bazzite-steam

# Fullscreen across multiple monitors
bindsym $mod+Ctrl+Shift+F floating toggle, border none, resize set width 4480px height 1440px, move absolute position 0 0, opacity 1