# Swayidle
# LT = time (seconds) before locking the screen
# OT = time (seconds) before turning the screen off
# ST = time (seconds) before suspend

# There are two instances of screen blackout and suspend commands because they must be run separately for when the screen is manually locked (i.e. idle immediately starts counting down)
# and when it is automatically locked by timeout (this timer will already have counted down all the way). Resume statements are per timeout statement.
# Lastly, ensure unlocking the session kills all instances of swaylock and the pgrep .. || statement ensures the screen only locks if swaylock is not already running.
exec LT=200 OT=60 ST=300 && swayidle -w \
	timeout $LT 'loginctl lock-session' \
		timeout $OT 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
			resume 'swaymsg "output * power on"' \
		timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && systemctl suspend' \
	timeout $((LT+OT)) 'swaymsg "output * power off"' \
		resume 'swaymsg "output * power on"' \
	timeout $((LT+ST)) 'systemctl suspend' \
	before-sleep 'pgrep -xu "$USER" swaylock >/dev/null || swaylock -f' \
	lock 'pgrep -xu "$USER" swaylock >/dev/null || swaylock -f' \
	unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'
