# Swayidle
# Lock session after 300 seconds
# Turn off the screen after 10 seconds of being locked
# Suspend after 300 seconds of being locked
# Also ensure that whenever sleep or loginctl lock-session is called, swaylock is called
exec swayidle -w \
	timeout 300 'loginctl lock-session' \
	timeout 10 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
	timeout 300 'pgrep -xu "$USER" swaylock >/dev/null && systemctl suspend' \
		resume 'swaymsg "output * power on"' \
	before-sleep 'loginctl lock-session' \
	lock 'swaylock -f'
