# GB keyboard layout
input type:keyboard {
    xkb_layout gb
    xkb_variant extd
    xkb_model logitech_base
}

# Disable mouse acceleration, set sensitivity to max
input type:pointer {
    accel_profile "flat"
    pointer_accel 0.5
}