#
# Resizing containers:
#
mode "resize" {
    # left will shrink the containers width
    # right will grow the containers width
    # up will shrink the containers height
    # down will grow the containers height
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # Ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"

# For use with VMs; passes input through by removing all keybinds
mode "passthrough" {
	bindsym $mod+Escape mode "default"
}
bindsym $mod+Shift+v mode "passthrough"

# For switching between layouts
mode "layouts" {
	# Split horizontally and vertically
	bindsym h splith; mode "default"
	bindsym v splitv; mode "default"

	# Layouts
	bindsym s layout stacking; mode "default"
	bindsym w layout tabbed; mode "default"
	bindsym e layout toggle split; mode "default"

	# Return to default mode
	bindsym Escape mode "default"
}
bindsym $mod+Return mode "layouts"
