# Resizing containers:
set $resize "resize container: hjkl/arrow keys and escape to exit"
mode $resize {
    # left will shrink the containers width
    # right will grow the containers width
    # up will shrink the containers height
    # down will grow the containers height
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # Ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # Return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode $resize

# For use with VMs; passes input through by removing all keybinds
set $passthrough "input passthrough: mod+escape to exit"
mode $passthrough {
	bindsym $mod+Escape mode "default"
}
bindsym $mod+Shift+v mode $passthrough

# For switching between layouts
set $layouts "layouts: h = splith, v = splitv, s = stacking, w = tabbed, e = toggle split and escape to exit"
mode $layouts {
	# Split horizontally and vertically
	bindsym h splith; mode "default"
	bindsym v splitv; mode "default"

	# Layouts
	bindsym s layout stacking; mode "default"
	bindsym w layout tabbed; mode "default"
	bindsym e layout toggle split; mode "default"

	# Return to default mode
	bindsym Escape mode "default"
}
bindsym $mod+Return mode $layouts

# For switching between workspace sets
set $ws_sets "workspace sets: 1 = 1-10, 2 = 11-20, 3 = 21-30 and escape to exit"
mode $ws_sets {
	bindsym 1 set $ws_1 1; set $ws_2 2; set $ws_3 3; set $ws_4 4; set $ws_5 5; set $ws_6 6; set $ws_7 7; set $ws_8 8; set $ws_9 9; set $ws_10 10; mode "default"
	bindsym 2 set $ws_1 11; set $ws_2 12; set $ws_3 13; set $ws_4 14; set $ws_5 15; set $ws_6 16; set $ws_7 17; set $ws_8 18; set $ws_9 19; set $ws_10 20; mode "default"
	bindsym 3 set $ws_1 21; set $ws_2 22; set $ws_3 23; set $ws_4 24; set $ws_5 25; set $ws_6 26; set $ws_7 27; set $ws_8 28; set $ws_9 29; set $ws_10 30; mode "default"

	bindsym Escape mode "default"
}
bindsym $mod+Shift+Return mode $ws_sets

set $ws_1 1
set $ws_2 2
set $ws_3 3
set $ws_4 4
set $ws_5 5
set $ws_6 6
set $ws_7 7
set $ws_8 8
set $ws_9 9
set $ws_10 10
