# Python language configuration
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

# GitHub Actions workflow language
[[language]]
name = "yaml"
file-types = [{ glob = ".github/workflows/*.yml" }, { glob = ".github/workflows/*.yaml" }]
language-servers = ["gh-actions-language-server"]
roots = [".github", ".git"]

# Bash definition for Helix editor with config.d for sway added
[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(shell|bash|zsh|sh)"
file-types = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = "sway/config.d/*.conf" },
  { glob = ".tmux.conf" },
  { glob = "tmux.conf" },
  { glob = ".sh_history" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = "bash_completion" },
  { glob = "bash-completion/completions/*" },
  { glob = "bash_completion.d/*" },
  { glob = "bin/activate" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
  { glob = ".xinitrc" }, # ~/.xinitrc
  { glob = "xinitrc" }, # /etc/X11/xinit/xinitrc
  { glob = ".xserverrc" }, # ~/.xserverrc
  { glob = "xserverrc" }, # /etc/X11/xinit/xserverrc
  { glob = "direnvrc" }, # ~/.config/direnv/direnvrc
]
shebangs = ["sh", "bash", "dash", "zsh"]
comment-token = "#"
language-servers = [ "bash-language-server" ]
indent = { tab-width = 2, unit = "  " }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.gh-actions-language-server]
command = 'gh-actions-language-server'
args = ['--stdio']
config = { sessionToken = ""}

[language-server.texlab.config.texlab.build]
onSave = true

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.rust-analyzer.config.check]
command = "clippy"
